name: Merge main into dev

on:
  push:
    branches:
      - main

jobs:
  update-dev:
    permissions: write-all
    name: update-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@users.noreply.github.com'
          # Create dev branch if it doesn't exist
          git checkout -b dev || git checkout dev
          git merge main --no-edit
          echo "Done with merge"
      - name: Push to dev
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          force: true