name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        set -ex
        export LOGIN=${{ github.actor }}
        echo "***"
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $LOGIN --password-stdin
        
        for i in docker/*
        do
            CONTAINER=$(basename $i)
            echo "Building $CONTAINER"
            export IMAGE=$(echo "${LOGIN,,}/augur_${CONTAINER,,}" | tr '[:upper:]' '[:lower:]')
            DOCKERFILE=docker/$CONTAINER/Dockerfile
            docker build . -f $DOCKERFILE --tag ghcr.io/${IMAGE}:latest
            docker push ghcr.io/${IMAGE}:latest
        done
